# Production configuration for Railway deployment
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "77dc002e0c0f5a42da57f99b2dd76b12"
name = "RGMN Functions"
handle = "rgmn-functions"
application_url = "https://rgmn-functions-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "rgmn-function-testing.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://rgmn-functions-production.up.railway.app/auth/callback",
  "https://rgmn-functions-production.up.railway.app/auth/shopify/callback",
  "https://rgmn-functions-production.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2025-07"

[pos]
embedded = false
